# 关键词回复配置（中文键名必须加引号）
[gh_81203cdf19a5]
"美团" = """
1⃣团团有20-10
👉http://dpurl.cn/jDkjQsAz
2⃣团团有38-13
👉http://dpurl.cn/UgHeiS8z
3⃣这里领商家券
👉https://kzurl08.cn/7b6FJR
4️⃣最新津贴入口🔍可搜索
👉mp://954gdrqAPD5PTXc
"""


"饿了么" = """
淘宝闪购搜【54188】
复制打开淘宝闪购补了 限时加码15-10~14
可点霸王茶姬 奈雪 喜茶等
￥WoP9UBGuRPM￥/ HU7405
"""
"接单查询" = """
http://waimaiyouhui.top/web/login
"""


"京东" = """
东子外卖分享好友各得21
https://u.jd.com/crQqGpW
已按优先级排序
https://u.jd.com/caQA07Q
https://u.jd.com/c1Qrtw7
https://u.jd.com/cDQqi4e
https://u.jd.com/cOQM7DT
https://u.jd.com/crQMj6K
https://u.jd.com/c1QZWre
爆品好价
https://u.jd.com/c1Qgk3N
自提好价
https://u.jd.com/cDQ1NRp
省钱卡2元可叠加
https://u.jd.com/caQqIWo
"""

"美团免配叠加津贴" = """
甜品饮品 mp://Im5pnmIHjwMwkAg
快餐简餐 mp://GFbf8UpuwNDSaxC
中式菜肴 mp://xwebk1KnjkQzV1g
西式美食 mp://LMYDkk8ERCfGMEh
美食小吃 mp://lXdjCsP4Dqyuvwr
火锅串串 mp://1vh8ilH6XHRLdDB
"""


"免配链接" = """
🚚 获取免配链接
请按照以下步骤操作：
先领大额包子
1⃣团团40-20和58-25
👉http://dpurl.cn/JqA3NkRz
2⃣团团有20-10
👉http://dpurl.cn/35yy5s7z
3⃣大众点评领45-20 38-18等
👉mp://6NIfy8LiSqiHguh
4️⃣美团双整点领38-18
👉mp://CEqkXw9LFe9kHDh
5⃣汉堡披萨大额红包40-20(周六日才有)
👉mp://h8qNnj6pKhJT80e
方式一：发送小程序卡片
1⃣ 点击下方链接进入小程序：
免配汇总1🔗mp://E1LUwc3hlFzLjjw
肯德基奶茶 津贴专区且免配送费
👉mp://UwWJyWasJo6sPqp
2⃣发送收藏的小程序卡片给我
💡 提示：系统会自动识别并生成免配链接，大众点评和美团都可以实现免配，必须在上面免配链接里的店铺才可以实现
"""

# 使用特殊标记来表示动态函数
"时间" = "__LAMBDA__:datetime.now()"

"接单时间" = {type="image", media_id="O1hJ0P6krWdL6IvswF9N9gOy-6V62GNT2Nbx8NIyxtZQ8ShmWnpRwSr-6cupgGkz"}


# 关键词回复配置2
[gh_4eb46eb83550]
"美团" = """
𝑺𝒕𝒆𝒑𝟏. 按序领美团外卖红包
#公众号:外卖羊毛王
❶ 先领日常𝟑𝟖-𝟏𝟖、𝟐𝟖-𝟏𝟐等
👉 https://kzurl03.cn/t3zIql
👉 https://kzurl07.cn/t3zImM
👉 mp://x76zDLrj0eX9Uzz
❷ 领美团𝟑𝟖-𝟏𝟖、𝟓𝟖-𝟐𝟎
👉 mp://q7j7uj1csxZyPlw
❸ 膨胀有𝟑𝟖-𝟏𝟗、𝟒𝟎-𝟐𝟎
👉 mp://WQM4UvrQra33r7i
👉 mp://fFBNGMVltHfXrgp

𝑺𝒕𝒆𝒑𝟐. 报名官方商家返现活动
👉 mp://CM8gCuv0bocueLr

𝑺𝒕𝒆𝒑𝟑. 商家🧧叠加券（必领⭐）
👉 https://kzurl13.cn/t3fRhB

𝑺𝒕𝒆𝒑𝟒. 叠天天津贴优惠下单
❶ 领天天津贴大🧧
👉 mp://RUtKrsd4KNPorBw
"""


"淘宝闪购" = """
淘宝闪购×千问三叠加，按下方顺序操作
💰保底-𝟑.𝟑，最高-𝟏𝟎.𝟐

❶ 先改地址浙江丽水松阳县
👉 mp://WExXqJ3JBdoxfKd
再领𝟏.𝟓通用叠加券
👉 mp://bVw2H9CnxN0hQcC
❷ 淘宝𝒂𝒑𝒑-闪购搜【124431】领免单卡
❸ 淘宝𝒂𝒑𝒑-闪购搜【499797】跳转千问下单

超大概率15-14/15
直接复'制'⬇ 打 开 🍑宝
￥44LYUFXWgHW￥/ HU7405
然后🍑闪购搜👉 499797
领学生专属叠加券
可与上面叠加成16-16/16-15
"""

"接单查询" = """
http://waimaiyouhui.top/web/login
"""

"京东" = """
京东𝟐～𝟓元喝霸王茶姬双杯/奈雪的茶/沪上阿姨/瑞幸咖啡等多种大牌奶茶教程（也可买饭吃）!!

𝟏、先领好运叠加券
❶ 𝟑-𝟐叠加
👉 https://u.jd.com/jGeI9P4
👉 https://u.jd.com/jDete7w
❷ 组团4-3叠加券
👉 #小程序://京东购物丨点外卖领国补/F3VDafhTZq7G6Gq

𝟐、京东-我的-互动游戏-领无门槛叠加红包

𝟑、领京东外卖券（𝟖-𝟏𝟖整点抢𝟏𝟕-𝟏𝟔、𝟖-𝟐𝟑每个整点抢𝟐𝟗-𝟐𝟎、𝟖-𝟐𝟎点每两小时抽一轮𝟐𝟗-𝟐𝟎）
👉 https://kzurl14.cn/t0hPta
"""

"美团免配叠加津贴" = """
甜品饮品mp://OQmjxUiZ2i8akyf
快餐简餐mp://cElY0dAbgQKXheg
中式菜肴mp://UcCLv4u1MrWFq3D
西式美食mp://PBvg53nskoGLSRc
炸鸡小吃mp://RABjMs5bKp66zni
火锅串串mp://3mb6vzaT6M2YYbd
"""

"圣诞帽" = """
http://waimaiyouhui.top/christmas-hat
"""

"优惠合集" = """
http://waimaiyouhui.top/boge
"""

"免配链接" = """
🚚 获取免配链接
请按照以下步骤操作：
先领大额包子
1⃣团团40-20和58-25
👉http://dpurl.cn/eiwhSzfz
2⃣团团有20-10
👉http://dpurl.cn/uMnKSd0z
3️⃣大众点评领45-20 38-18等
👉mp://221IqSWXvQKO7SF
4️⃣美团双整点领38-18
👉mp://x76zDLrj0eX9Uzz
5️⃣汉堡披萨大额红包40-20（周六日才有）
👉mp://9ROANiCRrH97eTk
方式一：发送小程序卡片
1️⃣ 点击下方链接进入小程序：
免配汇总1🔗mp://esr7cHk88p21jpK
免配汇总2🔗
mp://MqzLowrH9A94SMk
肯德基奶茶 津贴且免配送费
👉mp://UAStZnP16jVIIHs
2⃣发送收藏的小程序卡片给我
💡 提示：系统会自动识别并生成免配链接，大众点评和美团都可以实现免配
"""

"进群" = {type="image", media_id="EkJX0yZa4r8Gi9UYCc2UXfauAVChEL09QHHuyg8xXV40sWuOZtuDcNHabgLXI5og"}
"接单时间" = {type="image", media_id="EkJX0yZa4r8Gi9UYCc2UXawZsOwFEZh18gfnj1cpfXS3wP5OJCtYjT-zpMsaSq3m"}



# 关键词回复配置3
[gh_b882eacc1d73]
"美团" = """
美団吃喝玩乐 每日领
👉http://dpurl.cn/TGt1s9ez

美团闪购🧧天天领
👉http://dpurl.cn/fI6JGtEz

美团外卖大额🧧每日领
👉http://dpurl.cn/udDlXEwz
美団外荬🧧40-20 / 30-15
👉http://dpurl.cn/7l7eno8z

以下城市可用👇
深圳、杭州、天津、成都"""

"打车券" = """
🚗 滴滴打车虹包 
mp://FRk94Cmg1yYAtys
🐷花小猪
mp://U2GjpMFCIwe6hAA
💊饿了么买药
mp://gUeayGHLoOqCePd
💊美團买药
http://dpurl.cn/Phn0Eztz
"""

"淘宝闪购" = """
❶每日可领津贴叠加🧧
￥UmlyUEldiVp￥/ HU7405
复制打开淘宝🍑𝗧𝗮𝗼𝗕𝗮𝗼 𝗮𝗽𝗽  
或陶闪购搜【51510】

❷便利店商超零售叠加🧧
叮咚/盒马/天猫 /便利店等可用
￥7x5uUElU1P7￥/ HU7405
或陶闪购搜【287878】
复制打开淘宝🍑𝗧𝗮𝗼𝗕𝗮𝗼 𝗮𝗽𝗽  
"""

"京东" = """
东哥个位数点外買🚗

❶京东外賣劵先全領
https://u.jd.com/AgomPBP 
❷plus領5-5叠加劵
https://u.jd.com/AOoml4m
❸新的4-3叠加卷
https://u.jd.com/A6omWAE
https://u.jd.com/AOomEE4

❹20-15 和4-3 
https://u.jd.com/AGomlLE
"""

"美团免配叠加津贴" = """
甜品饮品mp://OQmjxUiZ2i8akyf
快餐简餐mp://cElY0dAbgQKXheg
中式菜肴mp://UcCLv4u1MrWFq3D
西式美食mp://PBvg53nskoGLSRc
炸鸡小吃mp://RABjMs5bKp66zni
火锅串串mp://3mb6vzaT6M2YYbd
"""



"进群入口" = {type="image", media_id="C4ZAfIm8QF6vUkBDLLIm7yh4HC9mzRCnD3JT_c6-H3kl2GyzIQTY10ADcg82UMxX"}
"商家代金卷使用教程" = {type="image", media_id="C4ZAfIm8QF6vUkBDLLIm736U7rjqkRiBqI5cNcputNB2b5sH7-bMQ3YewuI5dptn"}
"津贴使用教程" = {type="image", media_id="C4ZAfIm8QF6vUkBDLLIm71KThewSujP5eVzU4jVZC_iR93IF5ciN5Og-bqrd-36k"}
"每天首单千问立减攻略" = {type="image", media_id="C4ZAfIm8QF6vUkBDLLIm70-hM3XHUoHVN22VVgm5-33ltndgBxp6gu84Qa8_5LxZ"}

# 关键词回复配置4
[gh_2448df791452]
"美团" = """
美団吃喝玩乐 每日领
👉http://dpurl.cn/TGt1s9ez

美团闪购🧧天天领
👉http://dpurl.cn/fI6JGtEz

美团外卖大额🧧每日领
👉http://dpurl.cn/udDlXEwz
美団外荬🧧40-20 / 30-15
👉http://dpurl.cn/7l7eno8z

以下城市可用👇
深圳、杭州、天津、成都"""

"打车券" = """
🚗 滴滴打车虹包 
mp://FRk94Cmg1yYAtys
🐷花小猪
mp://U2GjpMFCIwe6hAA
💊饿了么买药
mp://gUeayGHLoOqCePd
💊美團买药
http://dpurl.cn/Phn0Eztz
"""

"淘宝闪购" = """
❶每日可领津贴叠加🧧
￥UmlyUEldiVp￥/ HU7405
复制打开淘宝🍑𝗧𝗮𝗼𝗕𝗮𝗼 𝗮𝗽𝗽  
或陶闪购搜【51510】

❷便利店商超零售叠加🧧
叮咚/盒马/天猫 /便利店等可用
￥7x5uUElU1P7￥/ HU7405
或陶闪购搜【287878】
复制打开淘宝🍑𝗧𝗮𝗼𝗕𝗮𝗼 𝗮𝗽𝗽  
"""

"京东" = """
东哥个位数点外買🚗

❶京东外賣劵先全領
https://u.jd.com/AgomPBP 
❷plus領5-5叠加劵
https://u.jd.com/AOoml4m
❸新的4-3叠加卷
https://u.jd.com/A6omWAE
https://u.jd.com/AOomEE4

❹20-15 和4-3 
https://u.jd.com/AGomlLE
"""

"美团免配叠加津贴" = """
甜品饮品mp://OQmjxUiZ2i8akyf
快餐简餐mp://cElY0dAbgQKXheg
中式菜肴mp://UcCLv4u1MrWFq3D
西式美食mp://PBvg53nskoGLSRc
炸鸡小吃mp://RABjMs5bKp66zni
火锅串串mp://3mb6vzaT6M2YYbd
"""


# 关键词回复配置5
[gh_bdfb8233fa30]
"美团" = """
美団吃喝玩乐 每日领
👉http://dpurl.cn/TGt1s9ez

美团闪购🧧天天领
👉http://dpurl.cn/fI6JGtEz

美团外卖大额🧧每日领
👉http://dpurl.cn/udDlXEwz
美団外荬🧧40-20 / 30-15
👉http://dpurl.cn/7l7eno8z

以下城市可用👇
深圳、杭州、天津、成都"""

"饿了么" = """
淘宝闪购搜【54188】
复制打开淘宝闪购补了 限时加码15-10~14
可点霸王茶姬 奈雪 喜茶等
￥WoP9UBGuRPM￥/ HU7405
"""

"京东" = """
东哥个位数点外買🚗

❶京东外賣劵先全領
https://u.jd.com/AgomPBP 
❷plus領5-5叠加劵
https://u.jd.com/AOoml4m
❸新的4-3叠加卷
https://u.jd.com/A6omWAE
https://u.jd.com/AOomEE4

❹20-15 和4-3 
https://u.jd.com/AGomlLE
"""

"美团免配叠加津贴" = """
甜品饮品mp://OQmjxUiZ2i8akyf
快餐简餐mp://cElY0dAbgQKXheg
中式菜肴mp://UcCLv4u1MrWFq3D
西式美食mp://PBvg53nskoGLSRc
炸鸡小吃mp://RABjMs5bKp66zni
火锅串串mp://3mb6vzaT6M2YYbd
"""
