from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODE_PORT_KEYS = {"dev": "WX_DEV_HTTP_PORT", "prod": "WX_HTTP_PORT"}
DEFAULT_PORTS = {"dev": "18080", "prod": "8080"}
CONF_DIR_CANDIDATES = (
    "/www/server/panel/vhost/nginx",
    "/www/server/nginx/conf/vhost",
    "/etc/nginx/conf.d",
    "/usr/local/openresty/nginx/conf/conf.d",
    "/usr/local/openresty/nginx/conf/vhost",
)
NGINX_BIN_CANDIDATES = (
    "/www/server/nginx/sbin/nginx",
    "/usr/local/openresty/nginx/sbin/nginx",
)
NGINX_CONF_CANDIDATES = (
    "/www/server/nginx/conf/nginx.conf",
    "/usr/local/openresty/nginx/conf/nginx.conf",
    "/etc/nginx/nginx.conf",
)
GENERATED_MARKER = "Generated by wx-coupon setup_nginx_proxy.py"


def _parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _normalize_base_url(value: str) -> str:
    normalized = str(value or "").strip().rstrip("/")
    if normalized and "://" not in normalized:
        normalized = "http://" + normalized
    return normalized


def _server_name_from_base_url(value: str) -> str:
    normalized = _normalize_base_url(value)
    if not normalized:
        return ""
    parsed = urlparse(normalized)
    return parsed.hostname or ""


def _validate_port(label: str, value: str) -> str:
    normalized = str(value or "").strip()
    if not normalized.isdigit():
        raise ValueError(f"{label} 必须是数字端口: {value}")
    port = int(normalized)
    if port < 1 or port > 65535:
        raise ValueError(f"{label} 超出合法端口范围: {port}")
    return str(port)


def _validate_server_name(value: str) -> str:
    normalized = str(value or "").strip()
    if not normalized:
        raise ValueError("server_name 不能为空；请传 --server-name 或配置 GO_SHORTLINK_PUBLIC_BASE_URL")
    if "://" in normalized or "/" in normalized:
        raise ValueError(f"server_name 只能是域名、IP 或 _，不要带协议和路径: {normalized}")
    if any(ch.isspace() for ch in normalized):
        raise ValueError(f"server_name 不能包含空白字符: {normalized}")
    return normalized


def _safe_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "-", value.strip() or "default").strip(".-")
    return cleaned or "default"


def _detect_conf_dir(explicit: str) -> Path:
    if explicit:
        return Path(explicit).expanduser().resolve()
    env_dir = os.getenv("WX_NGINX_CONF_DIR", "").strip()
    if env_dir:
        return Path(env_dir).expanduser().resolve()
    for candidate in CONF_DIR_CANDIDATES:
        path = Path(candidate)
        if path.exists():
            return path
    return Path("/etc/nginx/conf.d")


def _detect_nginx_bin(explicit: str) -> str:
    if explicit:
        return explicit
    env_bin = os.getenv("WX_NGINX_BIN", "").strip()
    if env_bin:
        return env_bin
    for candidate in NGINX_BIN_CANDIDATES:
        if Path(candidate).exists():
            return candidate
    return shutil.which("nginx") or "nginx"


def _detect_nginx_conf(explicit: str) -> str:
    if explicit:
        return explicit
    env_conf = os.getenv("WX_NGINX_CONF", "").strip()
    if env_conf:
        return env_conf
    for candidate in NGINX_CONF_CANDIDATES:
        if Path(candidate).exists():
            return candidate
    return ""


def _build_config(*, listen: str, server_name: str, upstream: str, access_log: str, error_log: str) -> str:
    return f"""# {GENERATED_MARKER}
server {{
    listen {listen};
    server_name {server_name};

    client_max_body_size 50m;
    access_log {access_log};
    error_log {error_log};

    location / {{
        proxy_pass {upstream};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "";
        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        proxy_buffering off;
        proxy_cache off;
    }}
}}
"""


def _find_existing_server_names(conf_dir: Path, server_name: str) -> list[Path]:
    if not conf_dir.exists():
        return []
    matches: list[Path] = []
    pattern = re.compile(r"\bserver_name\s+([^;]+);")
    for path in sorted(conf_dir.glob("*.conf")):
        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for match in pattern.finditer(content):
            names = {item.strip() for item in match.group(1).split() if item.strip()}
            if server_name in names:
                matches.append(path)
                break
    return matches


def _run_nginx_command(command: list[str]) -> tuple[int, str]:
    completed = subprocess.run(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    return completed.returncode, completed.stdout.strip()


def _nginx_base_command(nginx_bin: str, nginx_conf: str) -> list[str]:
    command = [nginx_bin]
    if nginx_conf:
        command.extend(["-c", nginx_conf])
    return command


def _install_config(path: Path, content: str, *, force: bool, backup: bool) -> Path | None:
    backup_path: Path | None = None
    if path.exists():
        current = path.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_MARKER not in current and not force:
            raise FileExistsError(f"目标配置已存在且不是本脚本生成，请加 --force 或换 --conf-name: {path}")
        if backup:
            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            backup_path = path.with_name(f"{path.name}.bak.{timestamp}")
            shutil.copy2(path, backup_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(f".{path.name}.tmp")
    temp_path.write_text(content, encoding="utf-8")
    os.replace(temp_path, path)
    return backup_path


def _rollback_config(path: Path, backup_path: Path | None, had_existing: bool) -> None:
    if backup_path and backup_path.exists():
        shutil.copy2(backup_path, path)
        return
    if not had_existing and path.exists():
        path.unlink()


def _emit_json(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["dev", "prod"], default="prod")
    parser.add_argument("--env-file", default=str(PROJECT_ROOT / ".env"))
    parser.add_argument("--server-name", default="", help="域名、服务器 IP 或 _；默认从 GO_SHORTLINK_PUBLIC_BASE_URL 推断")
    parser.add_argument("--public-base-url", default="", help="用于推断 server_name，例如 http://1.2.3.4")
    parser.add_argument("--port", default="", help="Docker 暴露到宿主机的 app 端口，默认读取 .env")
    parser.add_argument("--upstream", default="", help="完整上游地址，默认 http://127.0.0.1:<port>")
    parser.add_argument("--listen", default="80")
    parser.add_argument("--conf-dir", default="", help="Nginx server 配置目录；默认自动识别宝塔/Nginx/OpenResty")
    parser.add_argument("--conf-name", default="", help="配置文件名，默认 wx-coupon-<server_name>.conf")
    parser.add_argument("--access-log", default="")
    parser.add_argument("--error-log", default="")
    parser.add_argument("--nginx-bin", default="")
    parser.add_argument("--nginx-conf", default="")
    parser.add_argument("--install", action="store_true", help="写入配置文件；默认只打印 dry-run")
    parser.add_argument("--reload", action="store_true", help="install 后执行 nginx -t 并 reload")
    parser.add_argument("--force", action="store_true", help="允许覆盖非本脚本生成的目标配置")
    parser.add_argument("--replace-existing", action="store_true", help="同名 server_name 已存在时，覆盖已有配置文件")
    parser.add_argument("--no-backup", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    try:
        env_values = _parse_env(Path(args.env_file).expanduser().resolve())
        base_url = args.public_base_url or env_values.get("GO_SHORTLINK_PUBLIC_BASE_URL", "")
        server_name = _validate_server_name(args.server_name or _server_name_from_base_url(base_url))
        listen = _validate_port("listen", args.listen)
        port = _validate_port("port", args.port or env_values.get(MODE_PORT_KEYS[args.mode], "") or DEFAULT_PORTS[args.mode])
        upstream = str(args.upstream or f"http://127.0.0.1:{port}").strip().rstrip("/")
        if "://" not in upstream:
            upstream = "http://" + upstream
        conf_dir = _detect_conf_dir(args.conf_dir)
        conf_name = args.conf_name or f"wx-coupon-{_safe_name(server_name)}.conf"
        if not conf_name.endswith(".conf"):
            conf_name += ".conf"
        output_path = conf_dir / conf_name
        log_dir = "/www/wwwlogs" if Path("/www/wwwlogs").exists() else "/var/log/nginx"
        log_name = _safe_name(server_name)
        access_log = args.access_log or f"{log_dir}/wx-coupon-{log_name}.access.log"
        error_log = args.error_log or f"{log_dir}/wx-coupon-{log_name}.error.log"
        content = _build_config(
            listen=listen,
            server_name=server_name,
            upstream=upstream,
            access_log=access_log,
            error_log=error_log,
        )

        existing_paths = _find_existing_server_names(conf_dir, server_name)
        if existing_paths and output_path not in existing_paths:
            if not args.replace_existing:
                existing = ", ".join(str(path) for path in existing_paths)
                raise FileExistsError(
                    f"同名 server_name 已存在，避免生成重复 Nginx 配置；已有文件: {existing}。"
                    "确认要接管时加 --replace-existing --force"
                )
            output_path = existing_paths[0]

        nginx_bin = _detect_nginx_bin(args.nginx_bin)
        nginx_conf = _detect_nginx_conf(args.nginx_conf)
        backup_path: Path | None = None
        test_output = ""
        reload_output = ""
        if args.install:
            had_existing = output_path.exists()
            backup_path = _install_config(output_path, content, force=args.force, backup=not args.no_backup)
            if args.reload:
                test_command = _nginx_base_command(nginx_bin, nginx_conf) + ["-t"]
                test_status, test_output = _run_nginx_command(test_command)
                if test_status != 0:
                    _rollback_config(output_path, backup_path, had_existing)
                    raise RuntimeError(f"nginx -t 失败:\n{test_output}")
                reload_command = _nginx_base_command(nginx_bin, nginx_conf) + ["-s", "reload"]
                reload_status, reload_output = _run_nginx_command(reload_command)
                if reload_status != 0:
                    _rollback_config(output_path, backup_path, had_existing)
                    raise RuntimeError(f"nginx reload 失败:\n{reload_output}")

        payload = {
            "ok": True,
            "installed": bool(args.install),
            "reloaded": bool(args.install and args.reload),
            "mode": args.mode,
            "server_name": server_name,
            "listen": listen,
            "upstream": upstream,
            "conf_path": str(output_path),
            "backup_path": str(backup_path) if backup_path else "",
            "nginx_bin": nginx_bin,
            "nginx_conf": nginx_conf,
            "config": content,
            "nginx_test": test_output,
            "nginx_reload": reload_output,
        }
        if args.json:
            _emit_json(payload)
        else:
            print("SETUP_NGINX_PROXY_OK")
            print(f"mode={args.mode}")
            print(f"server_name={server_name}")
            print(f"listen={listen}")
            print(f"upstream={upstream}")
            print(f"conf_path={output_path}")
            if backup_path:
                print(f"backup_path={backup_path}")
            print("installed=1" if args.install else "installed=0 dry_run=1")
            if args.install and args.reload:
                print("reloaded=1")
            print("")
            print(content.rstrip())
        return 0
    except Exception as exc:
        if args.json:
            _emit_json({"ok": False, "error": exc.__class__.__name__, "message": str(exc)})
        else:
            print(f"SETUP_NGINX_PROXY_FAILED {exc.__class__.__name__}: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
